name: extra_market
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.1
  google_sign_in: ^5.4.2
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.3.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.4.0
  equatable: ^2.0.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

